SELECT NAME_EMPLOYEE,DATE_OF_BIRTH,SALARY,COUNTRY_NAME,CITY,STREET,HOUSE,
       ID_ADMINISTRATION,ID_DIRECTORS,ID_HRMANAGERS,ID_MARKETING,ID_MARKETOLOGS,ID_SALES,ID_DEVELOPMENT,ID_FRONTENDS,ID_BACKENDS
FROM  EMPLOYEES e

left join ADDRESSES a on e.ID = a.EMPLOYEES_ID
left join COUNTRY c  on c.ID = a.COUNTRY_ID

left join ADMINISTRATION ad  on ad.EMPLOYEES_ID = e.ID
left join MARKETING mr  on mr.EMPLOYEES_ID = e.ID
left join DEVELOPMENT dv  on dv.EMPLOYEES_ID = e.ID

left join DIRECTORS d  on d.ADMINISTRATION_ID = ad.ID_ADMINISTRATION
left join HRMANAGERS h  on h.ADMINISTRATION_ID = ad.ID_ADMINISTRATION
left join MARKETOLOGS m  on m.MARKETING_ID = mr.ID_MARKETING 
left join SALES s  on s.MARKETING_ID = mr.ID_MARKETING 
left join BACKENDS b  on b.DEVELOPMENT_ID = dv.ID_DEVELOPMENT 
left join FRONTENDS f  on f.DEVELOPMENT_ID = dv.ID_DEVELOPMENT 

order by e.NAME_EMPLOYEE asc;