select EMPLOYEES_ID,NAME_EMPLOYEE,DATE_OF_BIRTH,SALARY,COUNTRY_NAME,CITY,STREET,HOUSE from EMPLOYEES e
left join ADDRESSES a
on e.ID = a.EMPLOYEES_ID
left join COUNTRY c
on c.ID = a.COUNTRY_ID
WHERE a.CITY = "Kiev"
group by e.ID
having avg(e.SALARY)>1000
LIMIT 1000